grails-app/domain/nextho/User.groovy
package nextho

class User {
	private static final long serialVersionUID = 1

	transient springSecurityService

	String username
	String password
	Boolean enabled=true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
    String firstName
    String lastName
    String uuid=UUID.randomUUID().toString()
    String emailAddress

	static constraints = {
		username blank: false, unique: true
		password blank: false
	    firstName nullable: true,blank: true
        lastName nullable: true,blank: true
    }

	static mapping = {
		password column: '`password`'
	}

	static transients = ['fullName']



	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}

	String getFullName(){
		"${this.firstName?:''} ${this.lastName?:''}"

	}
}

grails-app/controllers/LoginController.groovy
import grails.converters.JSON

import javax.servlet.http.HttpServletResponse

import org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils

import org.springframework.security.authentication.AccountExpiredException
import org.springframework.security.authentication.CredentialsExpiredException
import org.springframework.security.authentication.DisabledException
import org.springframework.security.authentication.LockedException
import org.springframework.security.core.context.SecurityContextHolder as SCH
import org.springframework.security.web.WebAttributes
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter

class LoginController {

	/**
	 * Dependency injection for the authenticationTrustResolver.
	 */
	def authenticationTrustResolver

	/**
	 * Dependency injection for the springSecurityService.
	 */
	def springSecurityService

	/**
	 * Default action; redirects to 'defaultTargetUrl' if logged in, /login/auth otherwise.
	 */
	def index = {
		if (springSecurityService.isLoggedIn()) {


//			redirect uri: SpringSecurityUtils.securityConfig.successHandler.defaultTargetUrl
			redirect controller: 'mixPanel', action: "dashboard"
		}
		else {
			redirect action: 'auth', params: params
		}
	}

	/**
	 * Show the login page.
	 */
	def auth = {

		def config = SpringSecurityUtils.securityConfig

		if (springSecurityService.isLoggedIn()) {
			redirect uri: config.successHandler.defaultTargetUrl
			return
		}

		String view = 'auth'
		String postUrl = "${request.contextPath}${config.apf.filterProcessesUrl}"
		render view: view, model: [postUrl: postUrl,
								   rememberMeParameter: config.rememberMe.parameter]
	}

	/**
	 * The redirect action for Ajax requests.
	 */
	def authAjax = {
		response.setHeader 'Location', SpringSecurityUtils.securityConfig.auth.ajaxLoginFormUrl
		response.sendError HttpServletResponse.SC_UNAUTHORIZED
	}

	/**
	 * Show denied page.
	 */
	def denied = {
		if (springSecurityService.isLoggedIn() &&
				authenticationTrustResolver.isRememberMe(SCH.context?.authentication)) {
			// have cookie but the page is guarded with IS_AUTHENTICATED_FULLY
			redirect action: 'full', params: params
		}
	}

	/**
	 * Login page for users with a remember-me cookie but accessing a IS_AUTHENTICATED_FULLY page.
	 */
	def full = {
		def config = SpringSecurityUtils.securityConfig
		render view: 'auth', params: params,
				model: [hasCookie: authenticationTrustResolver.isRememberMe(SCH.context?.authentication),
						postUrl: "${request.contextPath}${config.apf.filterProcessesUrl}"]
	}

	/**
	 * Callback after a failed login. Redirects to the auth page with a warning message.
	 */
	def authfail = {

		def username = session[UsernamePasswordAuthenticationFilter.SPRING_SECURITY_LAST_USERNAME_KEY]
		String msg = ''
		def exception = session[WebAttributes.AUTHENTICATION_EXCEPTION]
		if (exception) {
			if (exception instanceof AccountExpiredException) {
				msg = g.message(code: "springSecurity.errors.login.expired")
			}
			else if (exception instanceof CredentialsExpiredException) {
				msg = g.message(code: "springSecurity.errors.login.passwordExpired")
			}
			else if (exception instanceof DisabledException) {
				msg = g.message(code: "springSecurity.errors.login.disabled")
			}
			else if (exception instanceof LockedException) {
				msg = g.message(code: "springSecurity.errors.login.locked")
			}
			else {
				msg = g.message(code: "springSecurity.errors.login.fail")
			}
		}

		if (springSecurityService.isAjax(request)) {
			render([error: msg] as JSON)
		}
		else {
			flash.message = msg
			redirect action: 'auth', params: params
		}
	}

	/**
	 * The Ajax success redirect url.
	 */
	def ajaxSuccess = {
		render([success: true, username: springSecurityService.authentication.name] as JSON)
	}

	/**
	 * The Ajax denied redirect url.
	 */
	def ajaxDenied = {
		render([error: 'access denied'] as JSON)
	}
}

grails-app/views/login/auth.gsp
%{--<html>--}%
%{--<head>--}%
%{--<meta name='layout' content='main'/>--}%
%{--<title><g:message code="springSecurity.login.title"/></title>--}%
%{--<style type='text/css' media='screen'>--}%
%{--#login {--}%
%{--margin: 15px 0px;--}%
%{--padding: 0px;--}%
%{--text-align: center;--}%
%{--}--}%

%{--#login .inner {--}%
%{--width: 340px;--}%
%{--padding-bottom: 6px;--}%
%{--margin: 60px auto;--}%
%{--text-align: left;--}%
%{--border: 1px solid #aab;--}%
%{--background-color: #f0f0fa;--}%
%{---moz-box-shadow: 2px 2px 2px #eee;--}%
%{---webkit-box-shadow: 2px 2px 2px #eee;--}%
%{---khtml-box-shadow: 2px 2px 2px #eee;--}%
%{--box-shadow: 2px 2px 2px #eee;--}%
%{--}--}%

%{--#login .inner .fheader {--}%
%{--padding: 18px 26px 14px 26px;--}%
%{--background-color: #f7f7ff;--}%
%{--margin: 0px 0 14px 0;--}%
%{--color: #2e3741;--}%
%{--font-size: 18px;--}%
%{--font-weight: bold;--}%
%{--}--}%

%{--#login .inner .cssform p {--}%
%{--clear: left;--}%
%{--margin: 0;--}%
%{--padding: 4px 0 3px 0;--}%
%{--padding-left: 105px;--}%
%{--margin-bottom: 20px;--}%
%{--height: 1%;--}%
%{--}--}%

%{--#login .inner .cssform input[type='text'] {--}%
%{--width: 120px;--}%
%{--}--}%

%{--#login .inner .cssform label {--}%
%{--font-weight: bold;--}%
%{--float: left;--}%
%{--text-align: right;--}%
%{--margin-left: -105px;--}%
%{--width: 110px;--}%
%{--padding-top: 3px;--}%
%{--padding-right: 10px;--}%
%{--}--}%

%{--#login #remember_me_holder {--}%
%{--padding-left: 120px;--}%
%{--}--}%

%{--#login #submit {--}%
%{--margin-left: 15px;--}%
%{--}--}%

%{--#login #remember_me_holder label {--}%
%{--float: none;--}%
%{--margin-left: 0;--}%
%{--text-align: left;--}%
%{--width: 200px--}%
%{--}--}%

%{--#login .inner .login_message {--}%
%{--padding: 6px 25px 20px 25px;--}%
%{--color: #c33;--}%
%{--}--}%

%{--#login .inner .text_ {--}%
%{--width: 120px;--}%
%{--}--}%

%{--#login .inner .chk {--}%
%{--height: 12px;--}%
%{--}--}%
%{--</style>--}%
%{--</head>--}%

%{--<body>--}%
%{--<div id='login'>--}%
%{--<div class='inner'>--}%
%{--<div class='fheader'><g:message code="springSecurity.login.header"/></div>--}%

%{--<g:if test='${flash.message}'>--}%
%{--<div class='login_message'>${flash.message}</div>--}%
%{--</g:if>--}%

%{--<form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off'>--}%
%{--<p>--}%
%{--<label for='username'><g:message code="springSecurity.login.username.label"/>:</label>--}%
%{--<input type='text' class='text_' name='j_username' id='username'/>--}%
%{--</p>--}%
%{----}%
%{--<p>--}%
%{--<label for='password'><g:message code="springSecurity.login.password.label"/>:</label>--}%
%{--<input type='password' class='text_' name='j_password' id='password'/>--}%
%{--</p>--}%
%{----}%
%{--<p id="remember_me_holder">--}%
%{--<input type='checkbox' class='chk' name='${rememberMeParameter}' id='remember_me' <g:if test='${hasCookie}'>checked='checked'</g:if>/>--}%
%{--<label for='remember_me'><g:message code="springSecurity.login.remember.me.label"/></label>--}%
%{--</p>--}%
%{----}%
%{--<p>--}%
%{--<input type='submit' id="submit" value='${message(code: "springSecurity.login.button")}'/>--}%
%{--</p>--}%
%{--</form>--}%
%{--</div>--}%
%{--</div>--}%
%{--<script type='text/javascript'>--}%
%{--<!----}%
%{--(function() {--}%
%{--document.forms['loginForm'].elements['j_username'].focus();--}%
%{--})();--}%
%{--// -->--}%
%{--</script>--}%
%{--</body>--}%
%{--</html>--}%


<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="CleverAdmin - Bootstrap Admin Template">
		<meta name="author" content="Łukasz Holeczek">
		<meta name="keyword" content="CleverAdmin, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
	    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="57x57" href="assets/ico/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="assets/ico/favicon.png">

	    <title>cleverAdmin - Bootstrap Admin Template</title>

	    <!-- Bootstrap core CSS -->
<asset:stylesheet href="css/bootstrap.min.css" />

		<!-- page css files -->
<asset:stylesheet href="css/font-awesome.min.css"/>
<asset:stylesheet href="css/jquery-ui.min.css" />

	    <!-- Custom styles for this template -->
<asset:stylesheet href="css/style.min.css" />

	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
	</head>
</head>

<body>
		<div class="container-fluid content">
		<div class="row">
					<div id="content" class="col-sm-12 full">
			<div class="row">
				<div class="login-box">

					<div class="header">
						Login to Issue Tracker
					</div>


					<div class="text-with-hr">
						<span>your username</span>
					</div>

					<form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off'>

						<fieldset class="col-sm-12">
							<div class="form-group">
							  	<div class="controls row">
									<div class="input-group col-sm-12">
										<input type='text' class='form-control text_' name='j_username' id='username'/>
										<span class="input-group-addon"><i class="fa fa-user"></i></span>
									</div>
							  	</div>
							</div>

							<div class="form-group">
							  	<div class="controls row">
									<div class="input-group col-sm-12">
										<input type='password' class='form-control text_' name='j_password' id='password'/>
										<span class="input-group-addon"><i class="fa fa-key"></i></span>
									</div>
							  	</div>
							</div>

							<div class="confirm">
								<input type="checkbox" name="remember"/>
								<label for="remember">Remember me</label>
							</div>

							<div class="row">
								<input type='submit' class="btn btn-lg btn-primary col-xs-12" id="submit" value='${message(code: "springSecurity.login.button")}'/>
								%{--<button type="submit" class="btn btn-lg btn-primary col-xs-12">Login</button>--}%

							</div>

						</fieldset>

					</form>

					<a class="pull-left" href="page-login.html#">Forgot Password?</a>
					<a class="pull-right" href="page-register.html">Sign Up!</a>

					<div class="clearfix"></div>

				</div>
			</div><!--/row-->

		</div>

				</div><!--/row-->

	</div><!--/container-->


	<!-- start: JavaScript-->
	<!--[if !IE]>-->

<asset:javascript src="js/jquery-3.1.0.min.js"/>

	<!--<![endif]-->

	<!--[if IE]>

<asset:javascript src="js/jquery-1.11.0.min.js"/>

	<![endif]-->

	<!--[if !IE]>-->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='assets/js/jquery-3.1.0.min.js'>"+"<"+"/script>");
		</script>

	<!--<![endif]-->

	<!--[if IE]>

		<script type="text/javascript">
	 	window.jQuery || document.write("<script src='assets/js/jquery-1.11.0.min.js'>"+"<"+"/script>");
		</script>

	<![endif]-->
	%{--<script src="assets/js/jquery-migrate-1.4.1.min.js"></script>--}%
<asset:javascript src="js/bootstrap.min.js"/>

<asset:javascript src="js/jquery-migrate-1.4.1.min.js"/>


<!-- page scripts -->
<asset:javascript src="js/jquery.icheck.min.js"/>

<!-- theme scripts -->
	<asset:javascript src="js/custom.min.js"/>
		<asset:javascript src="js/core.min.js"/>

<!-- inline scripts related to this page -->
<asset:javascript src="js/pages/login.js"/>

<!-- end: JavaScript-->

</body>
</html>

grails-app/views/login/dashboard.gsp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="layout" content="nextho"/>
    <title>Dashboard</title>
</head>
<body>


<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script>
    $( function() {
        $( "#datepicker" ).datepicker();
        $( "#datepickeTo" ).datepicker();

    } );
    $(".datepicker").click(function(){
        $( ".datepicker").hide()
    })
</script>
<br>
<br>
<div class="row">
    <g:form controller="mixPanel" action="fetchRecord"  name="fetchEvents" method="post"     >
        <div class="col-md-2">
            <p>From: <input type="text" id="datepicker" name="fromDate" required="required" placeholder="Date"></p></div>
        <div class="col-md-2"><p>To : <input type="text" id="datepickeTo" name="toDate" required="required" placeholder="Date"></p></div>
        <div class="col-md-2" style="
        margin-top: 16px;
        ">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-cubes"></i></span>
                <select name="event" class="form-control" id="accountType" required="required">
                    <option value="">Select Event</option>
                    <option value="page event">Page View</option>
                    <option value="button event">Button Click</option>
                </select>
            </div>
        </div>
        <div class="col-md-2" style="
        margin-top: 17px;
        ">
            <input type="submit" class="btn btn-primary btn-block" value="Submit"/>
        </div>
    </g:form>
</div>
<div class="row" style="
margin-top: -150px;
">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        <h2>Event Details</h2>
        <table class="table">
            <thead>
            <tr>
                <th>Event Type</th>
                <th>Event Id</th>
                <th>User Id</th>
                <th>User Firstname</th>
                <th>User Lastname</th>
                <th>User Email</th>
            </tr>
            </thead>
            <tbody>
            <g:each in="${eventList}" var="dataList" status="i">
                <tr>
                    <td>${dataList?.eventType}</td>
                    <td>${dataList?.eventId}</td>
                    <td>${dataList?.userId}</td>
                    <td>${dataList?.firstName}</td>
                    <td>${dataList?.lastName}</td>
                    <td>${dataList?.userEmailId}</td>
                </tr>
            </g:each>

            </tbody>
        </table>

    </div>
</div><!--/.row-->

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <h2>User Details</h2>
        <table class="table">
            <thead>
            <tr>
                <th>id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Last Seen</th>
            </tr>
            </thead>
            <tbody>
            <g:each in="${userList}" var="data" status="i">
                <tr class="success">
                    <td>${data.$distinct_id}</td>
                    <td>${data.$properties.$first_name}</td>
                    <td>${data.$properties.$last_name}</td>
                    <td>${data.$properties.$email}</td>
                    <td>${data.$properties.$last_seen}</td>
                </tr>
            </g:each>

            </tbody>
        </table>
    </div>
</div><!--/.row-->

</body>
</html>

grails-app/views/login/denied.gsp
<head>
<meta name='layout' content='main' />
<title><g:message code="springSecurity.denied.title" /></title>
</head>

<body>
<div class='body'>
	<div class='errors'><g:message code="springSecurity.denied.message" /></div>
</div>
</body>

grails-app/views/login/home.gsp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="layout" content="nextho"/>
    <title>Dashboard</title>
</head>
<body>



</body>
</html>